name = "Connect to Google Bigquery for Rust"
description = "Fastly Compute starter kit for Google Bigquery Connector."
authors = ["<devrel@fastly.com>"]
language = "rust"
manifest_version = 3

[scripts]
  build = "cargo build --profile release"

[local_server]

  [local_server.backends]

    [local_server.backends.bigquery]
      url = "https://bigquery.googleapis.com/"

    [local_server.backends.idp]
      url = "https://oauth2.googleapis.com/"
